### ISSUE TITLE
Google Fonts Montserrat no light

### ISSUE THREAD

**Issue by Joul420** [Joul420/PXLV3_Slicing#2]
Only normal 400 and bold 700

Should we make our webfont ?

**Comment by MickaelFranc** [comment]
Pourquoi en anglais dude ?
Sinon, il me semblait qu'on allait éviter les google font. Font-face avec Montserrat Hairline ou Montserrat Light ;)

**Comment by Joul420** [comment]
Oui pardon c'est parce que je quand je me parle a moi même, je me parle souvent en anglais xD

En effet j'ai viré google font et créé mon propre kit, ce sera dans le prochain pull ;)
